### ISSUE TITLE
option to mark ckan file to avoid overwriting by bot

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN-bot#11]
There is plenty situations when we need to fix something in ckan file but all changes will be overwritten by NetKAN-bot so we need hack .netkan files. It's annoying as hell especially when you need to just bump ksp_version etc.

**Comment by techman83** [comment]
@TeddyDD I think KSP-CKAN/CKAN#1160 probably addresses this requirement.

It'd be a non trivial task to implement something like this as we don't know in advance what netkan would spit out.

**Comment by TeddyDD** [comment]
@techman83 Yep, I forgot about this issue. Closing.

**Comment by techman83** [comment]
Awesome, thanks @TeddyDD
