### ISSUE TITLE
netkan-bot shouldn't break compatibility when a mod author updates ksp versions

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN-bot#26]
I noticed this commit: https://github.com/KSP-CKAN/CKAN-meta/commit/7a189015ff68eedd3e4a3c00ba9ef4606e451f00

Netkan-bot bumped the `ksp_version` of the mod from `1.0.2` to `1.0.4` because the author updated the kerbalstuff page. The problem is that now the mod can't be installed under `1.0.2` even though we know it's compatible.

To accommodate people who choose not to upgrade, netkan-bot should probably create a compatibility range (`ksp_min` and `ksp_max`) if a `ksp_version` change occurs without an associated new release.

**Comment by techman83** [comment]
@plague006 - I'll work out where to move this soon. But the bot just runs NetKAN.exe and commits what is outputted.

It is deliberately simple, so that NetKAN authors can be easily write inflatable metadata and test without needing to understand the infrastructure behind it.

**Comment by techman83** [comment]
Closing in favour of KSP-CKAN/CKAN#1310
