### ISSUE TITLE
OuterPlanetsMod Not Updating

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/NetKAN-bot#27]
Pinging @techman83 

`OuterPlanetsMod` has an update (`1.7.2`) from a couple of days ago that has yet to be processed. Running netkan locally generates the updated CKAN just fine. Are the logs for the netkan bot publicly available to see what's going on?

**Comment by techman83** [comment]
Not as yet unfortunately, there is a re-write of that service that is being reviewed. Once that's done I'm planning on working on making stuff like that available.

Currently the validation is barfing
```
netkan@ckan-bot:~/.NetKAN$ ./ckan-validate.py CKAN-meta/OuterPlanetsMod/OuterPlanetsMod-1-1.7.2.ckan 
Validating CKAN-meta/OuterPlanetsMod/OuterPlanetsMod-1-1.7.2.ckan.. Failed! See below for error description.
None is not of type u'string'

Failed validating u'type' in schema[u'properties'][u'resources'][u'properties'][u'repository']:
    {u'description': u'Mod repository',
     u'format': u'uri',
     u'type': u'string'}

On instance[u'resources'][u'repository']:
    None
```

**Comment by techman83** [comment]
I see, the spec says the repository must be a string. It's null for that mod and it fails validation. Anything that doesn't validate doesn't get committed and pushed.

**Comment by dbent** [comment]
I see, thanks. The Kerbal Stuff API is returning an empty string for the source code repository, not sure how that translates into a `null`, but I'll update NetKAN to handle that case.

Also, pinging @plague006 since he was interested

**Comment by techman83** [comment]
Oh awesome, I was just about to raise an issue. The indexer will pull the latest NetKAN artifact that will be built when something is merged into master. I'll leave it in your capable hands.

If it's a straight forward change I'll keep an eye on my on my email and merge it. Then the next run should sort out all that.
