### ISSUE TITLE
Epoch's cause a ':' in the Mirror Name

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-bot#47]
Colons cause the archive name to be rejected. Replacing colons with an underscore is likely the easiest solution.

**Comment by techman83** [comment]
@dbent pointed out that in the client it is replaced with a dash. Consistency will be good and will do the same here.

**Comment by techman83** [comment]
@dbent - your thoughts here. The Epochs are for the client ordering, the version is the same and the download is the same. We might double upload things with + without the epoch, when essentially they are the same.

**Comment by dbent** [comment]
> We might double upload things with + without the epoch, when essentially they are the same.

That should happen (at most) once per epoch change and epoch changes should be relatively rare. How much of a problem would a double upload be?

**Comment by plague006** [comment]
In addition 3/4 of epochs I personally add will be unnecessary moving forward after https://github.com/KSP-CKAN/CKAN/pull/1730 is merged and released.

**Comment by techman83** [comment]
Not a huge problem, more being a good netizen is high on my priority list. I've not noted huge amounts of them lately, so it should be ok. We can always address it if it becomes one.
