### ISSUE TITLE
Better Logging

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-bot#5]
We log failures, but we don't capture the why. That shouldn't be entirely difficult.

**Comment by mgsdk** [comment]
Should netkan have a return value for each regular failure case? e.g. 404 makes netkan return -10 etc? Or do we just parse the text output?

**Comment by pjf** [comment]
@mgsdk : We should definitely be returning '0' on success. Having per-error exit codes would be great, but I don't believe is something we do yet. :)

(Having 8-bit, positive integer codes is also most platform portable.)

**Comment by techman83** [comment]
That'd probably make catching them easier. But the errors are consistent, so should be able to filter and log them.
