### ISSUE TITLE
Web Accessible Logs

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-bot#6]
For @mgsdk :D - Depends on #5 

It'd be nice to at least have the logs accessible from the web. To begin with it'll probably just be the last couple of 100 lines poked into an S3 bucket.

**Comment by mgsdk** [comment]
:+1:

As long as it contains the entire last run I'll be happy.

**Comment by HebaruSan** [comment]
We've had this for a while now:  http://status.ksp-ckan.space/
