### ISSUE TITLE
`dzil install` is throttled by GitHub API

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-bot#68]
Trying to `dzil install` the NetKAN-bot according to the README causes it to run tests that use the GitHub API to inflate modules without an auth token. If you are actively developing functionality and so need to do this several times per hour, the tests can fail due to the API's throttling:

```json
{
  "message": "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Need some way to plug in an auth token for these tests to use. Currently it looks like they generate a fresh config object from scratch and don't attempt to source a token from any other files or environment variables.

Discovered while trying to port the bash version of #67 to Perl.

**Comment by techman83** [comment]
I'm glad you're taking a look at this stuff! The config should really be able to pull that from an environment variable. Which is how we'd want to pass stuff like this in when packaging it all up with docker.

You could add an environment variable check [here](https://github.com/KSP-CKAN/NetKAN-bot/blob/master/lib/App/KSP_CKAN/Tools/Config.pm#L103)
```perl
my $token = $ENV{'CKAN_GH_TOKEN'}
```
We'd need to decide which wins (config or environment) and build that assumption in.

**Comment by HebaruSan** [comment]
Well I think the real system (i.e., not-tests) is fine already. The config file is a perfectly suitable spot for the token and works well.

It's really just the tests that are the issue, because they don't read any existing config file; they make their own config from scratch so they can control the working dir and the repository and so on. So #70 checks `$ENV{GH_token}` in just the tests.

**Comment by techman83** [comment]
Yeah, it's better and works for now is good enough for me. Converting to docker is something I'd like to do, but making things environment variables can be a future task.
