### ISSUE TITLE
NetKAN Status Page

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-bot#7]
We could build a json structure and whip up a simple static page for the status. Bootstrap/Knockout can do all that work client side and we'd just sit it in an S3 bucket and poke an updated JSON file in there after every run.

If there are any web devs that want to knock something simple up (prefer something static for now - unless compelling reasons otherwise) - I'd be more than happy to produce some simple data structures to get started with.

**Comment by techman83** [comment]
A status file containing current status of all the NetKANs is updated after every indexing run. It contains a status object for each NetKAN, below gives examples of Inflated/Checked/Failed/Indexed. The intention being that when 'lite' indexing is implemented the differentiation between checked and inflated will become more important.

```json
{
    "MK2KSPIIntegration": {
        "failed": false,
        "last_checked": "2015-08-30T04:39:08Z",
        "last_error": null,
        "last_indexed": "2015-08-30T04:39:10Z",
        "last_inflated": "2015-08-30T04:39:10Z"
    },
    "MOVAP": {
        "failed": false,
        "last_checked": "2015-08-30T04:39:46Z",
        "last_error": null,
        "last_indexed": null,
        "last_inflated": "2015-08-30T04:39:48Z"
    },
    "MachGauge": {
        "failed": false,
        "last_checked": "2015-08-30T04:38:23Z",
        "last_error": null,
        "last_indexed": null,
        "last_inflated": "2015-08-30T04:38:25Z"
    },
    "MacrossValkyrieVf1": {
        "failed": true,
        "last_checked": "2015-08-30T04:38:25Z",
        "last_error": "Schema validation failed",
        "last_indexed": null,
        "last_inflated": "2015-08-30T04:38:27Z"
    }
}
```

Now to build an interface around the data!

**Comment by techman83** [comment]
techamn83/NetKAN-status -> http://status.ksp-ckan.org/

**Comment by plague006** [comment]
thank you!

**Comment by Dazpoet** [comment]
Now that's some truly sexy stuff!

**Comment by HebaruSan** [comment]
Presumably this can be closed now.  http://status.ksp-ckan.space/
