### ISSUE TITLE
Install on new system fails

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN-bot#77]
I built a new Ubuntu server, version 18.04.1
then followed all the instructions.  Everything worked until I tried the command:
dzil install
which failed with the following error:
```
[DZ] error running {{["cpanm", "."]}}
[DZ] install failed, left failed dist in place at .build/aF4iyMWE2T
[DZ] error running {{["cpanm", "."]}} at inline delegation in Dist::Zilla for logger->log_fatal (attribute declared in /home/ckan/perl5/lib/perl5/Dist/Zilla.pm at line 768) line 18.
```

I also see this line a lot in the log file:
`error: pathspec 'master' did not match any file(s) known to git.`

I did it both with the individual commands in the git repo, and with the overall one:

`cpanm App-KSP_CKAN-0.009.tar.gz
`

I got the same error both times

**Comment by HebaruSan** [comment]
What folder are you running that from? It kind of sounds like it can't find the dist.ini file.

**Comment by techman83** [comment]
We should package all these services up as docker files, I hadn't done a lot with docker when all this was developed. In answer to your question regarding multiple NetKAN bots, we may want to be careful how it's approached. The bot itself never "crashes", when it has stopped working it's been the Git repo that has become corrupt. If an individual run fails, it will try again on the next schedule. The status [site](http://status.ksp-ckan.space) consumes the status output by the main bot and the Mirroring uses the cache generated by the bot (but works without it).

**Comment by linuxgurugamer** [comment]
Oh, so the ini file needs to be created BEFORE the build?  I was following the instructions as listed, I'll try that.
If I run the bot on my server, will it be building the cache on my system?  or would it try to update the cache on the central system?

**Comment by HebaruSan** [comment]
The ini file isn't created at all, it's part of the repo. cpanm needs it to know what to do.

**Comment by techman83** [comment]
From memory I think it should complain or generate a file if it doesn't exist. Certainly doesn't need it to install.

For personal use, it'll work with whatever git repo you point it at (even a local filepath will work and is indeed how the tests are run). But do be careful, you have push access :slightly_smiling_face: - Also from a Kind Netizen perspective, too many of us hitting spacedock with our own bots too frequently may be a little unkind, but it will operate on whatever subset of Netkans you have.

Both my machines are Linux mint, of that equivalent Ubuntu version. How have you setup the Perl environment?

**Comment by HebaruSan** [comment]
I just had a similar or the same error, inspecting the log file revealed:

```
Can't locate Lexical/SealRequireHints.pm in @INC (you may need to install the Lexical::SealRequireHints module) (@INC contains: t/lib/ /home/paul/Downloads/KSP/NetKAN-bot/.build/EooCT7tqUl/blib/lib /home/paul/Downloads/KSP/NetKAN-bot/.build/EooCT7tqUl/blib/arch /home/paul/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/paul/perl5/lib/perl5 /home/paul/perl5/lib/perl5/5.26.1/x86_64-linux-gnu-thread-multi /home/paul/perl5/lib/perl5/5.26.1 /home/paul/perl5/lib/perl5/5.26.0/x86_64-linux-gnu-thread-multi /home/paul/perl5/lib/perl5/5.26.0 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.2 /usr/local/share/perl/5.26.2 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/paul/perl5/lib/perl5/Method/Signatures.pm line 6.
```

This fixed it:

```sh
cpanm Lexical::SealRequireHints
```

@linuxgurugamer, can you share your complete log file? It should be pointed out in a line like this:

```
! Installing . failed. See /home/user/.cpanm/work/1550449949.14077/build.log for details. Retry with --force to force install it.
```

**Comment by HebaruSan** [comment]
This repo doesn't need to be installed anymore, it's been replaced by https://github.com/KSP-CKAN/NetKAN-Infra
