### ISSUE TITLE
Staging Fails when Local Branch exists, but Remote removed

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-bot#85]
Staging use's an `identifier` branch when inflating the staged NetKAN. When the branch doesn't exist anywhere, it create's one locally, pushes it and opens a PR.

When it exists locally, but not upstream it fails and NetKAN bails out
```
netkan@ckan-bot:~$ netkan-indexer 
fatal: Couldn't find remote ref MechJeb2
```
A test case would be good for this. Then fixing it might involve pushing the branch without changes before inflating.

**Comment by HebaruSan** [comment]
Is this related to the removal of the 'staging' branch? I thought that a while back the bot was able to recreate the remote Kopernicus branch after deletion.

**Comment by techman83** [comment]
Hmm. I don't think so. I think it was blowing up before because of the staging branch. Now it's just highlighted something else. I know for sure there isn't a test case for this scenario.

**Comment by HebaruSan** [comment]
Hopefully this is a clue: When I search for that error, everyone seems to think it relates to pulling, not pushing. So maybe we end up trying to pull the identifier branch now somehow?

**Comment by techman83** [comment]
Yeah, that's correct.  But that _should_ be ok.
https://github.com/KSP-CKAN/NetKAN-bot/blob/master/lib/App/KSP_CKAN/Tools/Git.pm#L333

**Comment by techman83** [comment]
I actually can't replicate this that particular error. But I did find another issue relating to this #86
