### ISSUE TITLE
NetKAN commit hooks don't seem to be running

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-bot#89]
Lately, merging a NetKAN pull request doesn't update CKAN-meta quickly. The changes only take effect when the bot runs. This can make metadata contributors uneasy because we make changes and close their issues, but they don't see the effects for several more hours.

@techman83, can you please check whether there's an error condition in the server?

**Comment by techman83** [comment]
Yeah, the endpoint needs some work to allow it more openly. So it only allows port 80 from the github ranges. Which had changed. Updated those. Really would like to find some time to re-architect a lot of this stuff! Most of the DevOps is full automated at work now and it's a dream!

**Comment by HebaruSan** [comment]
Thanks!
